--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/15/2024 6:04:18 a. m.
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--

CREATE DATABASE hotel;
SET NAMES 'utf8';

--
-- Set default database
--
USE hotel;

--
-- Drop table `reservas`
--
DROP TABLE IF EXISTS reservas;

--
-- Drop table `habitacion`
--
DROP TABLE IF EXISTS habitacion;

--
-- Drop table `usuarios`
--
DROP TABLE IF EXISTS usuarios;

--
-- Set default database
--
USE hotel;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  id int NOT NULL AUTO_INCREMENT,
  email varchar(255) NOT NULL,
  nombre varchar(255) DEFAULT NULL,
  telefono varchar(255) DEFAULT NULL,
  password varchar(255) NOT NULL,
  role varchar(255) DEFAULT 'usuario',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 40,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `email` on table `usuarios`
--
ALTER TABLE usuarios
ADD UNIQUE INDEX email (email);

--
-- Create table `habitacion`
--
CREATE TABLE habitacion (
  id int NOT NULL AUTO_INCREMENT,
  numero varchar(20) NOT NULL,
  tipo varchar(50) DEFAULT NULL,
  descripcion varchar(255) DEFAULT NULL,
  precio int DEFAULT NULL,
  estado varchar(255) DEFAULT '1',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `reservas`
--
CREATE TABLE reservas (
  id int NOT NULL AUTO_INCREMENT,
  usuario_id int NOT NULL,
  habitacion_id int NOT NULL,
  entrada date DEFAULT NULL,
  salida date DEFAULT NULL,
  estado enum ('confirmada', 'cancelada', 'pendiente') DEFAULT 'pendiente',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 24,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE reservas
ADD CONSTRAINT reservas_ibfk_1 FOREIGN KEY (usuario_id)
REFERENCES usuarios (id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE reservas
ADD CONSTRAINT reservas_ibfk_2 FOREIGN KEY (habitacion_id)
REFERENCES habitacion (id);

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 'usuario@hotmail.com', 'ANDRES CARRILLO', '3217261132', '$2a$10$yFkOQioUTpZtCRj6MM2Og.eINDmLjb6b/ug2.BHHyMWJVS3lPsDte', 'usuario', '2024-11-14 10:11:32'),
(34, 'admin@admin.com', 'Administrador', '3214568798', '$2a$10$JfpTD585PD8ONoNSAX227OfDCebHbW1WiZtUKWCwTfN/rv2fZ5qBG', 'admin', '2024-11-15 02:38:13'),
(38, 'asskdkjsds@gmail.com', 'saasdslñkjdsdlkdjkl', '32322323', '$2a$10$va6j3smrpcZRzLC0YTXeDeNBlSu2ubZpM/uyqW7jwZ7DgD/wge/0K', 'usuario', '2024-11-15 05:39:48'),
(39, 'andres@hotmail.com', 'ANDRES JIMENEZ', '233233232', '$2a$10$yoK38y6Z6N2PCn426bjfFuPkcaNoL3Z8ViqFvXqBWD7wffd64Iqde', 'usuario', '2024-11-15 06:01:10');

-- 
-- Dumping data for table habitacion
--
INSERT INTO habitacion VALUES
(1, '101', 'CAMA PERSONAL', 'CAMA PARA UNA PERSONA CON AIRE ....', 120000, 'Mantenimiento', '2024-11-14 10:45:34'),
(2, '102', 'PRESIDENCIAL', 'CAMA PARA UNA PERSONA CON AIRE, TV, VISTA AL MAR', 52000, 'Disponible', '2024-11-14 11:28:27'),
(3, '103-1', 'SUITE', 'AMOBLADA', 250000, 'Disponible', '2024-11-15 04:20:20'),
(4, '103', 'CAMA PERSONAL', 'CAMA PERSONAL UN SOLO CUERPO', 152000, 'Disponible', '2024-11-15 04:21:47'),
(5, '104', 'CAMA PERSONAL', 'djkhdsjhsjhsjh', 200000, 'Reservada por evento', '2024-11-15 05:38:46');

-- 
-- Dumping data for table reservas
--
INSERT INTO reservas VALUES
(20, 1, 1, '2024-11-15', '2024-11-16', 'confirmada', '2024-11-15 05:37:58'),
(21, 38, 1, '2024-11-27', '2024-11-30', 'confirmada', '2024-11-15 05:42:25'),
(22, 38, 1, '2024-11-18', '2024-11-19', 'confirmada', '2024-11-15 05:56:58'),
(23, 39, 3, '2024-11-15', '2024-11-18', 'confirmada', '2024-11-15 06:01:56');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;